project: ORGANIZATION/home-credit
name: home-credit-default-risk
parameters:
  # Data preparation
  n_cv_splits: 5
  validation_size: 0.2
  stratified_cv: True
  shuffle: 1

  # Random forest
  rf:
    n_estimators:
      min: 100
      max: 1500
    criterion:
      - gini
      - entropy
    max_depth:
      min: 3
      max: 15
    max_features:
      min: 0.01
      max: 1.0

  # Optuna parameters
  optuna:
    n_trials: 15
